# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4(self):
    self.driver.get("http://localhost/Hotel-Management-System/index.php")
    self.driver.set_window_size(1366, 738)
    self.driver.find_element(By.NAME, "Username").click()
    self.driver.find_element(By.NAME, "Username").send_keys("Rohit Lokhande")
    self.driver.find_element(By.NAME, "Password").send_keys("123")
    self.driver.find_element(By.ID, "userlogin").click()
    self.driver.find_element(By.NAME, "Email").click()
    self.driver.find_element(By.NAME, "Email").send_keys("lokhanderohit2020@gmail.com")
    self.driver.find_element(By.NAME, "user_login_submit").click()
    self.driver.find_element(By.LINK_TEXT, "Facilites").click()
    self.driver.find_element(By.LINK_TEXT, "contact us").click()
  
